export const BASE_URL = 'https://v2.api.noroff.dev/holidaze'
export const Venues = '/venues'
export const Profile = '/profiles'
export const Bookings = '/bookings'
export const Login = 'https://v2.api.noroff.dev/auth/login'
export const Register = 'https://v2.api.noroff.dev/auth/register'